# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: [ "master" ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Release-Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: broadcast
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
      - uses: ./.github/actions/ci-setup
#         if: ${{ steps.release.outputs.release_created }}
#       - uses: ./.github/actions/ci-checks
        if: ${{ steps.release.outputs.release_created }}
      - run: pnpm zip
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        if: ${{ steps.release.outputs.release_created }}
        with:
          name: broadcast
          path: ./dist
          if-no-files-found: error
          retention-days: 90
